### ISSUE TITLE
How to set the angle parameter

### ISSUE THREAD

**Issue by IqbalBintangsyah** [mich1342/ros2_laser_scan_merger#13]
Hello! Thank you for sharing this package!

I would like to ask you about the angle parameters. I have a robot with 2 LiDARS in the front and the rear. Both has 120 degree FOV from 30 deg to 150 deg.
For the `ros2_laser_scan_merger` package, I believe that the `AngleMax` and `AngleMin` parameters are both set 150 and 30 respectively.
For the `pointcloud_to_laserscan` package, based on what i read on their github page, `angle_max` and `angle_min` are the minimum and maximum angle for the incoming point cloud set in radians. But in my case, the incoming point cloud would be (i guess) -150 ~ -30, and then 30 ~ 150. How should i set this parameter?

btw my current `/scan` data are all `inf`, I think my parameters are bad? Or is it because of other things?

Thank you!

This is my current parameter file
```yaml
/ros2_laser_scan_merger:
  ros__parameters:
    flip1: false
    flip2: false
    inverse1: true
    inverse2: true
    laser1Alpha: 0.0
    laser1AngleMax: 150.0
    laser1AngleMin: 30.0
    laser1B: 0
    laser1G: 0
    laser1R: 255
    laser1XOff: 0.56
    laser1YOff: 0.0
    laser1ZOff: 0.105
    laser2Alpha: 180.0
    laser2AngleMax: -30.0
    laser2AngleMin: -150.0
    laser2B: 255
    laser2G: 0
    laser2R: 0
    laser2XOff: -0.43
    laser2YOff: 0.0
    laser2ZOff: 0.105
    pointCloudTopic: cloud_in
    pointCloutFrameId: laser
    qos_overrides./parameter_events.publisher.depth: 1000
    # qos_overrides./parameter_events.publisher.durability: volatile
    # qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: best_effort
    scanTopic1: /lidar_front_to_slam
    scanTopic2: /lidar_back_to_slam
    show1: true
    show2: true
    use_sim_time: true

/pointcloud_to_laserscan:
  ros__parameters:
    angle_increment: 0.0087
    # angle_max: 1.5708
    # angle_min: -1.5708
    angle_max: 3.14
    angle_min: -3.14
    inf_epsilon: 1.0
    max_height: 0.105
    min_height: 0.105
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          # durability: volatile
          # history: keep_last
          reliability: best_effort
    queue_size: 16
    range_max: 12.0
    range_min: 0.0
    scan_time: 0.3333
    target_frame: laser
    transform_tolerance: 0.01
    use_inf: true
    use_sim_time: true
```
